captainVersion: 4
networks:
    search:
        driver: bridge
services:
    $$cap_appname:
        image: zhenghaoz/gorse-in-one:$$cap_Gorse_version
        restart: always
        command:
            - "--playground"
        caproverExtra:
            containerHttpPort: 8088
caproverOneClickApp:
    variables:
        - id: $$cap_Gorse_version
          label: Gorse Version
          defaultValue: 'latest'
          description: Check out their docker page for the valid tags https://hub.docker.com/_/zhenghaoz/gorse-in-one?tab=tags
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: 'An open-source recommender system service written in Go'
        end: Gorse is deployed and the dashboard is available from http://$$cap_appname.$$cap_root_domain.
    isOfficial: true
    description: 'Gorse An open-source recommender system service written in Go'
    documentation: https://hub.docker.com/_/zhenghaoz/gorse-in-one?tab=description
