captainVersion: 4
networks:
    search:
        driver: bridge
services:
    $$cap_appname-db:
        image: postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: $$cap_postgres_user
            POSTGRES_PASSWORD: $$cap_postgres_password
            POSTGRES_DB: $$cap_postgres_database_name
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        image: kestra/kestra:$$cap_kestra_version
        volumes:
          - $$cap_appname-data:/app/storage
          - /var/run/docker.sock:/var/run/docker.sock
        entrypoint: /bin/bash
        command:
          - -c
          - /app/kestra server standalone --worker-thread=128
        restart: always
        environment:
            KESTRA_CONFIGURATION: |
              datasources:
                postgres:
                  url: jdbc:postgresql://srv-captain--$$cap_appname-db:5432/$$cap_postgres_database_name
                  driverClassName: org.postgresql.Driver
                  username: $$cap_postgres_user
                  password: $$cap_postgres_password
              kestra:
                server:
                  basic-auth:
                    enabled: false
                    username: admin
                    password: kestra
                repository:
                  type: postgres
                storage:
                  type: local
                  local:
                    base-path: "/app/storage"
                queue:
                  type: postgres
                tasks:
                  tmp-dir:
                    path: /tmp/kestra-wd/tmp
                url: http://localhost:8080/
        caproverExtra:
            containerHttpPort: 8080
caproverOneClickApp:
    variables:
        - id: $$cap_kestra_version
          label: Kestra Version
          defaultValue: 'latest-full'
          description: Check out their docker page for the valid tags https://hub.docker.com/r/kestra/kestra/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_version
          label: Postgres Version
          defaultValue: '15'
          description: Check out their docker page for the valid tags https://hub.docker.com/_/postgres/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_user
          label: Postgres User
          defaultValue: 'kestra'
        - id: $$cap_postgres_password
          label: Postgres Password
          defaultValue: 'kestra@123'
        - id: $$cap_postgres_database_name
          label: Postgres Database Name
          defaultValue: 'kestra'
        

    instructions:
        start: 'Kestra, Open Source Declarative Data Orchestration'
        end: Kestra is deployed and the dashboard is available from http://$$cap_appname.$$cap_root_domain.
    isOfficial: true
    description: 'Kestra, Open Source Declarative Data Orchestration'
    documentation: https://hub.docker.com/r/kestra/kestra
