captainVersion: 4
networks:
    search:
        driver: bridge
services:
    $$cap_appname_api:
        image: tracardi/tracardi-api:$$cap_tracardi_version
        restart: always
        environment:
            ELASTIC_HOST: http://srv-captain--$$cap_appname_elasticsearch:9200
            REDIS_HOST: redis://srv-captain--$$cap_appname_redis:6379
            LOGGING_LEVEL: $$cap_LOGGING_LEVEL
            DEMO: $$cap_DEMO
            PRODUCTION: $$cap_PRODUCTION
        caproverExtra:
            containerHttpPort: 80
    $$cap_appname_gui:
        image: tracardi/tracardi-gui:$$cap_tracardi_version
        restart: always
        depends_on:
          - $$cap_appname_api
        environment:
            API_URL: $$cap_API_URL
        caproverExtra:
            containerHttpPort: 80
    $$cap_appname_elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:$$cap_elasticsearch_version
        restart: always
        environment:
            bootstrap.memory_lock: "true"
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            discovery.type: single-node
            xpack.security.enabled: "false"
            cluster.name: contextElasticSearch
    $$cap_appname_redis:
        image: redis
        restart: always
    $$cap_appname_worker:
        image: tracardi/update-worker:$$cap_tracardi_version
        restart: always
        environment:
          REDIS_HOST: redis://srv-captain--$$cap_appname_redis:6379
caproverOneClickApp:
    variables:
        - id: $$cap_tracardi_version
          label: Tracardi Version
          defaultValue: '0.8.1-rc3'
          description: Check out their docker page for the valid tags https://hub.docker.com/_/tracardi/tracardi-api/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_elasticsearch_version
          label: Elasticsearch Version
          defaultValue: '7.13.2'
          description: Check out their docker page for the valid tags https://hub.docker.com/_/elasticsearch/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_LOGGING_LEVEL
          label: Logging Level
          description: Logging Level
          defaultValue: 'info'
        - id: $$cap_DEMO
          label: Is Demo
          description: Is Demo
          defaultValue: 'yes'
        - id: $$cap_PRODUCTION
          label: Is Production
          description: Is Production
          defaultValue: 'no'
        - id: $$cap_API_URL
          label: Api Url
          description: Api Url
          defaultValue: https://$$cap_appname_api.$$cap_root_domain

    instructions:
        start: 'Tracardi: The Open Source Customer Data Platform (CDP)'
        end: Tracardi is deployed and the dashboard is available from http://$$cap_tracardi-gui.$$cap_root_domain.
    isOfficial: true
    description: 'Tracardi: The Open Source Customer Data Platform (CDP)'
    documentation: https://hub.docker.com/_/tracardi/tracardi-api
