captainVersion: 4
networks:
    search:
        driver: bridge
services:
    $$cap_appname:
        image: apache/unomi:$$cap_Unomi_version
        restart: always
        caproverExtra:
            containerHttpPort: 8181
caproverOneClickApp:
    variables:
        - id: $$cap_Unomi_version
          label: Apache Unomi Version
          defaultValue: '2.1.0'
          description: Check out their docker page for the valid tags https://hub.docker.com/_/apache/unomi?tab=tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_ELASTICSEARCH_HOST
          label: Elasticsearch Host
          description: Elasticsearch Host
          defaultValue: 'elasticsearch'
        - id: $$cap_ELASTICSEARCH_PORT
          label: Elasticsearch Port
          description: Elasticsearch Port
          defaultValue: '9200'
    instructions:
        start: "Apache Unomi™: The Open Source Customer Data Platform (CDP)"
        end: Apache Unomi is deployed and the dashboard is available from http://$$cap_appname.$$cap_root_domain.
    isOfficial: true
    description: "Apache Unomi™: The Open Source Customer Data Platform (CDP)"
    documentation: https://hub.docker.com/_/apache/unomi?tab=description
