captainVersion: 4
networks:
    search:
        driver: bridge
services:
    $$cap_appname:
        image: bavaan/vendure:$$cap_Vendure_version
        restart: always
        caproverExtra:
            containerHttpPort: 3000
caproverOneClickApp:
    variables:
        - id: $$cap_Vendure_version
          label: Vendure Version
          defaultValue: '1.7.1'
          description: Check out their docker page for the valid tags https://hub.docker.com/_/bavaan/vendure?tab=tags
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: Vendure is an open source headless ecommerce
        end: Vendure is deployed and the dashboard is available from http://$$cap_appname.$$cap_root_domain.
    isOfficial: true
    description: Vendure, formerly known as Headless Ecommerce, is a suite of open-source business apps written in Python and released under the AGPL license.
    documentation: https://hub.docker.com/_/bavaan/vendure?tab=description
